// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <eosio/vm/backend.hpp>

using namespace eosio;
using namespace eosio::vm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <simd_load64_lane_0_wasm>", "[simd_load64_lane_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_load64_lane.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "v128.load64_lane_0", UINT32_C(0), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1", UINT32_C(1), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_0_offset_0", make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1_offset_1", make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_0_align_1", UINT32_C(0), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_0_align_2", UINT32_C(0), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_0_align_4", UINT32_C(0), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_0_align_8", UINT32_C(0), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(506097522914230528u,0u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1_align_1", UINT32_C(1), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1_align_2", UINT32_C(1), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1_align_4", UINT32_C(1), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
   CHECK(bkend.call_with_return("env", "v128.load64_lane_1_align_8", UINT32_C(1), make_v128_i64(0u,0u))->to_v128() == make_v128_i64(0u,578437695752307201u));
}

BACKEND_TEST_CASE( "Testing wasm <simd_load64_lane_1_wasm>", "[simd_load64_lane_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_load64_lane.1.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_load64_lane_2_wasm>", "[simd_load64_lane_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_load64_lane.2.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_load64_lane_3_wasm>", "[simd_load64_lane_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_load64_lane.3.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

