// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <eosio/vm/backend.hpp>

using namespace eosio;
using namespace eosio::vm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_0_wasm>", "[simd_f32x4_rounding_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(0u,0u,0u,0u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1u,1u,1u,1u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2147483649u,2147483649u,2147483649u,2147483649u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(8388608u,8388608u,8388608u,8388608u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2155872256u,2155872256u,2155872256u,2155872256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1056964608u,1056964608u,1056964608u,1056964608u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(3204448256u,3204448256u,3204448256u,3204448256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1086918619u,1086918619u,1086918619u,1086918619u))->to_v128() == make_v128_f32(1088421888u,1088421888u,1088421888u,1088421888u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(3234402267u,3234402267u,3234402267u,3234402267u))->to_v128() == make_v128_f32(3233808384u,3233808384u,3233808384u,3233808384u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u))->to_v128() == make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u))->to_v128() == make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u))->to_v128() == make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u))->to_v128() == make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2143289344u,2143289344u,2143289344u,2143289344u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(4290772992u,4290772992u,4290772992u,4290772992u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(2141192192u,2141192192u,2141192192u,2141192192u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.ceil", make_v128_f32(4288675840u,4288675840u,4288675840u,4288675840u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(0u,0u,0u,0u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1u,1u,1u,1u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2147483649u,2147483649u,2147483649u,2147483649u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(8388608u,8388608u,8388608u,8388608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2155872256u,2155872256u,2155872256u,2155872256u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1056964608u,1056964608u,1056964608u,1056964608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(3204448256u,3204448256u,3204448256u,3204448256u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1086918619u,1086918619u,1086918619u,1086918619u))->to_v128() == make_v128_f32(1086324736u,1086324736u,1086324736u,1086324736u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(3234402267u,3234402267u,3234402267u,3234402267u))->to_v128() == make_v128_f32(3235905536u,3235905536u,3235905536u,3235905536u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u))->to_v128() == make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u))->to_v128() == make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u))->to_v128() == make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u))->to_v128() == make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2143289344u,2143289344u,2143289344u,2143289344u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(4290772992u,4290772992u,4290772992u,4290772992u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(2141192192u,2141192192u,2141192192u,2141192192u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.floor", make_v128_f32(4288675840u,4288675840u,4288675840u,4288675840u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(0u,0u,0u,0u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1u,1u,1u,1u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2147483649u,2147483649u,2147483649u,2147483649u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(8388608u,8388608u,8388608u,8388608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2155872256u,2155872256u,2155872256u,2155872256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1056964608u,1056964608u,1056964608u,1056964608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(3204448256u,3204448256u,3204448256u,3204448256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1086918619u,1086918619u,1086918619u,1086918619u))->to_v128() == make_v128_f32(1086324736u,1086324736u,1086324736u,1086324736u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(3234402267u,3234402267u,3234402267u,3234402267u))->to_v128() == make_v128_f32(3233808384u,3233808384u,3233808384u,3233808384u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u))->to_v128() == make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u))->to_v128() == make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u))->to_v128() == make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u))->to_v128() == make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2143289344u,2143289344u,2143289344u,2143289344u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(4290772992u,4290772992u,4290772992u,4290772992u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(2141192192u,2141192192u,2141192192u,2141192192u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.trunc", make_v128_f32(4288675840u,4288675840u,4288675840u,4288675840u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(0u,0u,0u,0u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1u,1u,1u,1u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2147483649u,2147483649u,2147483649u,2147483649u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(8388608u,8388608u,8388608u,8388608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2155872256u,2155872256u,2155872256u,2155872256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1056964608u,1056964608u,1056964608u,1056964608u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(3204448256u,3204448256u,3204448256u,3204448256u))->to_v128() == make_v128_f32(2147483648u,2147483648u,2147483648u,2147483648u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u))->to_v128() == make_v128_f32(1065353216u,1065353216u,1065353216u,1065353216u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u))->to_v128() == make_v128_f32(3212836864u,3212836864u,3212836864u,3212836864u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1086918619u,1086918619u,1086918619u,1086918619u))->to_v128() == make_v128_f32(1086324736u,1086324736u,1086324736u,1086324736u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(3234402267u,3234402267u,3234402267u,3234402267u))->to_v128() == make_v128_f32(3233808384u,3233808384u,3233808384u,3233808384u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u))->to_v128() == make_v128_f32(2139095039u,2139095039u,2139095039u,2139095039u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u))->to_v128() == make_v128_f32(4286578687u,4286578687u,4286578687u,4286578687u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u))->to_v128() == make_v128_f32(2139095040u,2139095040u,2139095040u,2139095040u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u))->to_v128() == make_v128_f32(4286578688u,4286578688u,4286578688u,4286578688u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u))->to_v128() == make_v128_f32(1290500515u,1290500515u,1290500515u,1290500515u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u))->to_v128() == make_v128_f32(1820282235u,1820282235u,1820282235u,1820282235u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(760819711u,760819711u,760819711u,760819711u))->to_v128() == make_v128_f32(0u,0u,0u,0u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u))->to_v128() == make_v128_f32(1536271028u,1536271028u,1536271028u,1536271028u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u))->to_v128() == make_v128_f32(1695654580u,1695654580u,1695654580u,1695654580u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u))->to_v128() == make_v128_f32(1376887476u,1376887476u,1376887476u,1376887476u));
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2143289344u,2143289344u,2143289344u,2143289344u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(4290772992u,4290772992u,4290772992u,4290772992u))->to_v128() == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(2141192192u,2141192192u,2141192192u,2141192192u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
   CHECK(bkend.call_with_return("env", "f32x4.nearest", make_v128_f32(4288675840u,4288675840u,4288675840u,4288675840u))->to_v128() == v128_matcher{nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{},nan_arithmetic_t{}});
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_17_wasm>", "[simd_f32x4_rounding_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.17.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_18_wasm>", "[simd_f32x4_rounding_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.18.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_19_wasm>", "[simd_f32x4_rounding_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.19.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_20_wasm>", "[simd_f32x4_rounding_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.20.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_21_wasm>", "[simd_f32x4_rounding_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.21.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_22_wasm>", "[simd_f32x4_rounding_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.22.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_23_wasm>", "[simd_f32x4_rounding_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.23.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <simd_f32x4_rounding_24_wasm>", "[simd_f32x4_rounding_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_f32x4_rounding.24.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

